import Head from "next/head";
import React from "react";
import Navbar from "./Navbar";
import Sidebar from "./Sidebar";

type TChildren = { children: React.ReactNode };

function Layout({ children }: TChildren) {
  return (
    <>
      <Head>
        <title>Whatever You Watch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen fixed flex flex-col h-screen">
        <Navbar />
        <div className="w-full  h-[90%] flex">
          <Sidebar />
          <div className="w-full h-full overflow-auto">{children}</div>
        </div>
      </div>
    </>
  );
}

export default Layout;
